# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import scrapData


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1126, 840)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(440, 60, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.startScrapping = QtWidgets.QPushButton(Dialog)
        self.startScrapping.setGeometry(QtCore.QRect(340, 180, 101, 28))
        self.startScrapping.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.startScrapping.setObjectName("startScrapping")
        self.pauseScrapping = QtWidgets.QPushButton(Dialog)
        self.pauseScrapping.setGeometry(QtCore.QRect(950, 180, 101, 28))
        self.pauseScrapping.setObjectName("pauseScrapping")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(630, 190, 55, 16))
        self.label_2.setObjectName("label_2")
        self.time = QtWidgets.QLabel(Dialog)
        self.time.setGeometry(QtCore.QRect(700, 190, 55, 16))
        self.time.setObjectName("time")
        self.progressBarOfScrapping = QtWidgets.QProgressBar(Dialog)
        self.progressBarOfScrapping.setGeometry(QtCore.QRect(460, 760, 381, 23))
        self.progressBarOfScrapping.setProperty("value", 50)
        self.progressBarOfScrapping.setObjectName("progressBarOfScrapping")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(260, 240, 20, 451))
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 230, 1121, 20))
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(610, 790, 71, 16))
        self.label_3.setObjectName("label_3")
        self.sortingAlgorithm = QtWidgets.QComboBox(Dialog)
        self.sortingAlgorithm.setGeometry(QtCore.QRect(40, 500, 181, 22))
        self.sortingAlgorithm.setObjectName("sortingAlgorithm")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingAlgorithm.addItem("")
        self.sortingOrder = QtWidgets.QComboBox(Dialog)
        self.sortingOrder.setGeometry(QtCore.QRect(40, 550, 181, 22))
        self.sortingOrder.setObjectName("sortingOrder")
        self.sortingOrder.addItem("")
        self.sortingOrder.addItem("")
        self.searchAlgorithm = QtWidgets.QComboBox(Dialog)
        self.searchAlgorithm.setGeometry(QtCore.QRect(40, 450, 181, 22))
        self.searchAlgorithm.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.searchAlgorithm.setToolTipDuration(14)
        self.searchAlgorithm.setObjectName("searchAlgorithm")
        self.searchAlgorithm.addItem("")
        self.searchAlgorithm.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 131, 111))
        self.label_4.setLineWidth(-2)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/Umair Ahmed/Desktop/1-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.searchText = QtWidgets.QLineEdit(Dialog)
        self.searchText.setGeometry(QtCore.QRect(40, 320, 121, 22))
        self.searchText.setObjectName("searchText")
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setGeometry(QtCore.QRect(170, 320, 51, 21))
        self.searchButton.setObjectName("searchButton")
        self.multiSorting = QtWidgets.QCheckBox(Dialog)
        self.multiSorting.setGeometry(QtCore.QRect(40, 650, 131, 20))
        self.multiSorting.setObjectName("multiSorting")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(270, 240, 851, 451))
        self.tableWidget.setRowCount(14000)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Mining of World Universities"))
        self.startScrapping.setText(_translate("Dialog", "Start Scrapping"))
        self.pauseScrapping.setText(_translate("Dialog", "Pause Scrapping"))
        self.label_2.setText(_translate("Dialog", "Timming:"))
        self.time.setText(_translate("Dialog", "00:00:00"))
        self.label_3.setText(_translate("Dialog", "scrapping....."))
        self.sortingAlgorithm.setCurrentText(_translate("Dialog", "Merge Sort"))
        self.sortingAlgorithm.setItemText(0, _translate("Dialog", "Merge Sort"))
        self.sortingAlgorithm.setItemText(1, _translate("Dialog", "Radix Sort"))
        self.sortingAlgorithm.setItemText(2, _translate("Dialog", "Quick Sort"))
        self.sortingAlgorithm.setItemText(3, _translate("Dialog", "Bubble Sort"))
        self.sortingAlgorithm.setItemText(4, _translate("Dialog", "Comb Sort"))
        self.sortingAlgorithm.setItemText(5, _translate("Dialog", "Counting Sort"))
        self.sortingAlgorithm.setItemText(6, _translate("Dialog", "Bucket Sort"))
        self.sortingAlgorithm.setItemText(7, _translate("Dialog", "Flash Sort"))
        self.sortingAlgorithm.setItemText(8, _translate("Dialog", "Heap Sort"))
        self.sortingAlgorithm.setItemText(9, _translate("Dialog", "Shell Sort"))
        self.sortingAlgorithm.setItemText(10, _translate("Dialog", "Insertion Sort"))
        self.sortingAlgorithm.setItemText(11, _translate("Dialog", "Selection Sort"))
        self.sortingAlgorithm.setItemText(12, _translate("Dialog", "Tim Sort"))
        self.sortingOrder.setItemText(0, _translate("Dialog", "Ascending"))
        self.sortingOrder.setItemText(1, _translate("Dialog", "Descending"))
        self.searchAlgorithm.setItemText(0, _translate("Dialog", "Binary Search"))
        self.searchAlgorithm.setItemText(1, _translate("Dialog", "Linear Search"))
        self.searchButton.setText(_translate("Dialog", "Search"))
        self.multiSorting.setText(_translate("Dialog", "Multiple Sorting"))
        #####Our Code
        
        
         
        self.startScrapping.clicked.connect(self.start)
        self.pauseScrapping.clicked.connect(self.pause)
        
        
        
    def start(self,Dialog):
        scrapData.scrapPermission=True
        scrapData.StartScraping()
    def pause(self,Dialog):
        scrapData.scrapPermission=False
           #######End


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
